### ISSUE TITLE
Home route not working in not found page

### ISSUE THREAD

**Issue by Sriver27** [anups1ngh/Tasty-treats#11]
![not_found](https://github.com/anups1ngh/Tasty-treats/assets/75061992/47dcc949-92d0-452f-9df8-3a6c93f260b4)

**Comment by acelanoit** [comment]
Hello Sriver27, I would like to give this a try, would it be ok if I did? Could you please assign the issue to me?

**Comment by anups1ngh** [comment]
Hii @acelanoit ! yaa sure you can do this . i will assign this issue to you

**Comment by anups1ngh** [comment]
Hey @acelanoit ! mainly whenever we are searching for restaurant which doesn't exist then this page will show up and as this is already a homepage that's why it is not redirecting to home page. so what you can do is whenever we are entering a text in searchbar and not found page showup . you can add clear button in search bar to clear the search input like

<img width="960" alt="image" src="https://github.com/anups1ngh/Tasty-treats/assets/86849540/e03514f2-02c6-46f4-a1a7-bc6d39da9261">

and style the clear button

**Comment by anups1ngh** [comment]
<img width="943" alt="image" src="https://github.com/anups1ngh/Tasty-treats/assets/86849540/59b10fb7-8db2-4142-bf48-b2f782ce4975">

i have fixed the issue now it is working perfectly

**Comment by acelanoit** [comment]
> Hey @acelanoit ! mainly whenever we are searching for restaurant which doesn't exist then this page will show up and as this is already a homepage that's why it is not redirecting to home page. so what you can do is whenever we are entering a text in searchbar and not found page showup . you can add clear button in search bar to clear the search input like
> 
> <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/86849540/285651756-e03514f2-02c6-46f4-a1a7-bc6d39da9261.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwMDg3NDMsIm5iZiI6MTcwMTAwODQ0MywicGF0aCI6Ii84Njg0OTU0MC8yODU2NTE3NTYtZTAzNTE0ZjItMDJjNi00NmY0LWExYTctYmM2ZDM5ZGE5MjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTI2VDE0MjA0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MGVkMGMwNGI5MWJhODNmOGRkOGU3YWQwN2JlMjc1YTYxZWE2YzE5YzRiNzNlMzYxZWQxYzc3ZDEzODgxNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Rd98jujRyEWp1x6d1Fvh-5JjZjMPpADNKkLlq6tr06I">
> and style the clear button

Thanks for clarifying!

Sure, that's one way to do it, or you could leave the button and simply clear the input and reload the page upon clicking on the "Back to Home" button.

I was going to handle this tomorrow as I'm out of town for the weekend, didn't realize it was that urgent, glad to hear you're happy with the outcome, though (:
